"""
summary_analysis.py
===================
Comparative dual-axis chart: AI corporate adoption rate vs. global
data center electricity consumption, 2020–2024.

This is the most ORIGINAL chart in the project.
No single published source makes this exact comparison.
The Stanford AI Index covers adoption. The IEA covers energy.
This script synthesizes both and asks: are they growing proportionally?

REQUIRED INPUTS (generated by other scripts):
  data/corporate_adoption_clean.csv   → from corporate_adoption.py
  data/iea_energy.csv           → from energy_analysis.py

Run those scripts first, or this script will fall back to hardcoded values.
"""

import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.ticker as mticker
from pathlib import Path

# ── PATHS ─────────────────────────────────────────────────────────────────────
BASE_DIR    = Path(__file__).resolve().parent.parent
DATA_DIR    = BASE_DIR / "data"
VISUALS_DIR = BASE_DIR / "visuals"
VISUALS_DIR.mkdir(exist_ok=True)

# ── LOAD ADOPTION DATA ────────────────────────────────────────────────────────
adopt_path = DATA_DIR / "corporate_adoption_clean.csv"
if adopt_path.exists():
    adopt = pd.read_csv(adopt_path, skipinitialspace=True)
    adopt.columns = adopt.columns.str.strip().str.lower().str.replace(" ", "_")
else:
    adopt = pd.DataFrame({
        "year":         [2020, 2021, 2022, 2023, 2024],
        "adoption_pct": [  50,   56,   50,   55,   78],
    })
    print("⚠ corporate_adoption_clean.csv not found — using fallback values.")

# ── LOAD ENERGY DATA ──────────────────────────────────────────────────────────
energy_path = DATA_DIR / "iea_energy.csv"
if energy_path.exists():
    energy = pd.read_csv(energy_path, skipinitialspace=True)
    energy.columns = energy.columns.str.strip().str.lower().str.replace(" ", "_")
else:
    energy = pd.DataFrame({
        "year":         [2020, 2021, 2022, 2023, 2024],
        "total_twh":    [ 270,  298,  325,  360,  415],
        "is_projected": [False,False,False,False,False],
    })
    print("⚠ iea_energy.csv not found — using fallback values.")

# ── MERGE ON SHARED YEARS (observed only) ─────────────────────────────────────
energy_obs = energy[energy["is_projected"] == False].copy() if "is_projected" in energy.columns else energy.copy()
merged = pd.merge(
    adopt[["year","adoption_pct"]],
    energy_obs[["year","total_twh"]],
    on="year", how="inner"
).sort_values("year").reset_index(drop=True)

if merged.empty:
    raise ValueError(
        "No overlapping years between adoption and energy datasets. "
        "Check that both CSVs cover at least some of 2020–2024."
    )

print("\nMerged dataset for comparison:")
print(merged.to_string(index=False))

# ── GROWTH RATES (original analysis) ──────────────────────────────────────────
merged["adopt_yoy"]  = merged["adoption_pct"].pct_change() * 100
merged["energy_yoy"] = merged["total_twh"].pct_change() * 100

print("\nYear-over-year growth rates:")
print(merged[["year","adopt_yoy","energy_yoy"]].dropna().to_string(index=False))

avg_adopt  = merged["adopt_yoy"].dropna().mean()
avg_energy = merged["energy_yoy"].dropna().mean()
print(f"\n→ Avg annual adoption growth:  {avg_adopt:+.1f}%")
print(f"→ Avg annual energy growth:    {avg_energy:+.1f}%")
print(f"→ Energy growing {avg_energy/avg_adopt:.1f}x faster than adoption breadth")

# ── DUAL-AXIS PLOT ─────────────────────────────────────────────────────────────
fig, ax1 = plt.subplots(figsize=(11, 6))
fig.patch.set_facecolor("#f5f2eb")
ax1.set_facecolor("#f5f2eb")

color_adopt  = "#2d4a5c"
color_energy = "#c84b2f"

# Left axis: adoption
ax1.plot(
    merged["year"], merged["adoption_pct"],
    color=color_adopt, linewidth=2.8, marker="o",
    markersize=7, label="Org. AI adoption rate (%)", zorder=5
)
ax1.set_ylabel("% of Organizations Using AI", fontsize=10, color=color_adopt)
ax1.tick_params(axis="y", colors=color_adopt)
ax1.set_ylim(0, 100)
ax1.yaxis.set_major_formatter(mticker.PercentFormatter(xmax=100, decimals=0, symbol="%"))

# Right axis: energy
ax2 = ax1.twinx()
ax2.set_facecolor("#f5f2eb")
ax2.plot(
    merged["year"], merged["total_twh"],
    color=color_energy, linewidth=2.8, marker="s",
    markersize=7, linestyle="--", label="Data center energy (TWh)", zorder=5
)
ax2.set_ylabel("Data Center Electricity (TWh)", fontsize=10, color=color_energy)
ax2.tick_params(axis="y", colors=color_energy)
ax2.set_ylim(0, merged["total_twh"].max() * 1.3)

# Shared x-axis
ax1.set_xlabel("Year", fontsize=10, color="#555")
ax1.set_xticks(merged["year"])
ax1.tick_params(axis="x", colors="#555")
ax1.spines[["top"]].set_visible(False)
ax2.spines[["top"]].set_visible(False)
ax1.spines[["left"]].set_color(color_adopt)
ax2.spines[["right"]].set_color(color_energy)
ax1.spines["bottom"].set_color("#d4cfc6")
ax1.grid(axis="y", color="#d4cfc6", linewidth=0.7, alpha=0.5, zorder=0)

# ChatGPT annotation
ax1.axvline(x=2022, color="#888", linewidth=0.9, linestyle=":", alpha=0.5)
ax1.text(2022.05, 8, "ChatGPT\nlaunched",
         fontsize=7.5, color="#888", alpha=0.8, style="italic")

# Combined legend
lines1, labels1 = ax1.get_legend_handles_labels()
lines2, labels2 = ax2.get_legend_handles_labels()
ax1.legend(lines1 + lines2, labels1 + labels2,
           loc="upper left", fontsize=9, framealpha=0.7)

fig.suptitle(
    "AI Corporate Adoption vs. Data Center Energy Consumption, 2020–2024",
    fontsize=13, fontweight="bold", y=1.01, color="#0f1117"
)
ax1.set_title(
    "Energy demand grows faster than adoption breadth — the cost of AI at scale",
    fontsize=9, color="#555", pad=6, style="italic"
)

fig.text(
    0.99, 0.01,
    "Sources: Stanford AI Index 2025 (McKinsey data) · IEA Energy and AI (2025)",
    ha="right", va="bottom", fontsize=7, color="#999", style="italic"
)

plt.tight_layout()
out_path = VISUALS_DIR / "comparative_chart.png"
plt.savefig(out_path, dpi=150, bbox_inches="tight")
print(f"\n✓ Chart saved → {out_path}")
plt.show()